spring:
  profiles: inmemory
  inmemory-datasource:
    url: jdbc:h2:mem:migration;DB_CLOSE_ON_EXIT=TRUE;
    username: appuser
    password: 2hdsy7sgz
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    connection-test: SELECT 1 FROM DUAL;
    schema: classpath:sql/inmemory/schema.sql
    data: classpath:sql/inmemory/import.sql
    initialize: true
