INSERT INTO monitor(before, after) VALUES('China', 'makumba');
INSERT INTO monitor(before, after) VALUES('India', 'makumba');
INSERT INTO monitor(before, after) VALUES('USA', 'makumba');
INSERT INTO monitor(before, after) VALUES('Indonesia', 'makumba');
INSERT INTO monitor(before, after) VALUES('Brazil', 'makumba');
INSERT INTO monitor(before, after) VALUES('Pakistan', 'makumba');
INSERT INTO monitor(before, after) VALUES('Nigeria', 'makumba');
INSERT INTO monitor(before, after) VALUES('Bangladesh', 'makumba');
INSERT INTO monitor(before, after) VALUES('Nigeria', 'makumba');
INSERT INTO monitor(before, after) VALUES('Russia', 'makumba');
INSERT INTO monitor(before, after) VALUES('Japan', 'makumba');
INSERT INTO monitor(before, after) VALUES('Mexico', 'makumba');
INSERT INTO monitor(before, after) VALUES('Philippines', 'makumba');
INSERT INTO monitor(before, after) VALUES('Ethiopia', 'makumba');
INSERT INTO monitor(before, after) VALUES('Vietnam', 'makumba');
INSERT INTO monitor(before, after) VALUES('Egypt', 'makumba');
INSERT INTO monitor(before, after) VALUES('Germany', 'makumba');
INSERT INTO monitor(before, after) VALUES('the Congo', 'makumba');
INSERT INTO monitor(before, after) VALUES('Iran', 'makumba');
INSERT INTO monitor(before, after) VALUES('Turkey', 'makumba');
INSERT INTO monitor(before, after) VALUES('Thailand', 'makumba');
INSERT INTO monitor(before, after) VALUES('France', 'makumba');
INSERT INTO monitor(before, after) VALUES('United Kingdom', 'makumba');
INSERT INTO monitor(before, after) VALUES('South Africa', 'makumba');
INSERT INTO monitor(before, after) VALUES('Myanmar', 'makumba');
INSERT INTO monitor(before, after) VALUES('South Korea', 'makumba');
INSERT INTO monitor(before, after) VALUES('Colombia', 'makumba');
INSERT INTO monitor(before, after) VALUES('Kenya', 'makumba');
INSERT INTO monitor(before, after) VALUES('Spain', 'makumba');
INSERT INTO monitor(before, after) VALUES('Argentina', 'makumba');
INSERT INTO monitor(before, after) VALUES('Ukraine', 'makumba');
INSERT INTO monitor(before, after) VALUES('Sudan', 'makumba');
INSERT INTO monitor(before, after) VALUES('Algeria', 'makumba');
INSERT INTO monitor(before, after) VALUES('Poland', 'makumba');